### ISSUE TITLE
My website (Guy Baz)

### ISSUE THREAD

**Issue by G-S-Baz** [szabgab/wis-python-bootcamp-2023-12#1]
My website page: https://g-s-baz.github.io/guy-baz.github.io/aboutme
My respiratory: https://github.com/G-S-Baz/guy-baz.github.io

**Comment by szabgab** [comment]
nice, but change the repo name to `g-s-baz.github.io` and then the address would be https://g-s-baz.github.io/
You can change in the Settings of your repo: https://github.com/G-S-Baz/guy-baz.github.io

**Comment by G-S-Baz** [comment]
Thanks, changed.
New link: https://g-s-baz.github.io/

**Comment by szabgab** [comment]
nice
