### ISSUE TITLE
Sarit Aharoni's public page

### ISSUE THREAD

**Issue by saritaharoni** [szabgab/wis-python-bootcamp-2023-12#13]
page: https://saritaharoni.github.io/
repository: https://github.com/saritaharoni/python-course

**Comment by szabgab** [comment]
So you have a page, but it is empty. please fill it with some content before I can accept it.

**Comment by saritaharoni** [comment]
updated:)

**Comment by szabgab** [comment]
I will probably give 50 for this.
Look at what the other did if you'd like to get a better grade.

**Comment by saritaharoni** [comment]
Can I get some more time? Because I wouldn't accomplish it until 20.

Sarit

**Comment by szabgab** [comment]
Then do it later.

**Comment by saritaharoni** [comment]
Thank you for the extra time.
I hope it's better now.

**Comment by szabgab** [comment]
nice
