### ISSUE TITLE
Stav's public page 

### ISSUE THREAD

**Issue by stavhir** [szabgab/wis-python-bootcamp-2023-12#2]
page: http://stavhir.github.io/
repository: https://github.com/stavhir/bootcampgit

**Comment by szabgab** [comment]
The former is a link to your github account, not to the web page created by "GitHub Pages". Given your username is `stavhir` you need to create a repository called `stavhir.github.io` and then the web site will be at http://stavhir.github.io

**Comment by stavhir** [comment]
I fixed it and now there's a page: http://stavhir.github.io/

**Comment by szabgab** [comment]
It now works, now add some content like the others have
