### ISSUE TITLE
Golda's profile and repository

### ISSUE THREAD

**Issue by goldahg** [szabgab/wis-python-bootcamp-2023-12#20]
My profile: https://github.com/goldahg/goldahg.github.io
My repository: goldahg.github.io

**Comment by szabgab** [comment]
nice, but maybe you'd also want to add your name to that page and maybe a few links. See what the others did.

**Comment by goldahg** [comment]
> nice, but maybe you'd also want to add your name to that page and maybe a few links. See what the others did.

Sure, I added those

**Comment by szabgab** [comment]
thanks
