### ISSUE TITLE
Doreen's Github 

### ISSUE THREAD

**Issue by doreenpa** [szabgab/wis-python-bootcamp-2023-12#22]
https://github.com/doreenpa

**Comment by szabgab** [comment]
This is a link to your GitHub account.
The link to the web site and the link to the source of the web site are missing

**Comment by doreenpa** [comment]
You didnt see a link in both of them?

קבל ‏Outlook עבור Android‏<https://aka.ms/AAb9ysg>
________________________________

**Comment by szabgab** [comment]
In both there was a link, but not to what I asked.

**Comment by szabgab** [comment]
See #24
