### ISSUE TITLE
Nadavs project proposal

### ISSUE THREAD

**Issue by nadavhen** [szabgab/wis-python-bootcamp-2023-12#26]
https://github.com/nadavhen/NadavFinalProject

**Comment by szabgab** [comment]
This looks good, though I'd probably change the name of the repo to reflect what it does. e.g.  `PCR primers designer`.
You can do this in the Settings menu of the repo.
If you do so let me know (by adding a new comment with the new link here) so I can update in our README file.

**Comment by szabgab** [comment]
Oh and one more note, you are not the only Nadav in this course :smile:

**Comment by nadavhen** [comment]
Sorry, you are right this is Nadav Hen's final project and here is for the renamed repository
https://github.com/nadavhen/PCR-primer-designer
