### ISSUE TITLE
Our project (Golda, Doreen, Stav)

### ISSUE THREAD

**Issue by goldahg** [szabgab/wis-python-bootcamp-2023-12#28]
https://github.com/goldahg/Project/tree/main

**Comment by szabgab** [comment]
This looks good

* Please rename the repo to reflect what the project does (and not "Project")  - you can do so in the "Settings"
* Please link to the web page of each one of you in the Readme
* Please describe how the files look like and add at least one to the repo, but make sure it was anonymized - so no any personal identification of the patient was replaced by some other data.

**Comment by szabgab** [comment]
Comment here when you are done so I can check it and I can add the link of the repo to our README

**Comment by goldahg** [comment]
Done!

**Comment by szabgab** [comment]
enjoy!
