### ISSUE TITLE
Ori and Noa project proposal

### ISSUE THREAD

**Issue by NoaNai** [szabgab/wis-python-bootcamp-2023-12#29]
Link to Ori Berman and Noa Nairner's project repository;
https://github.com/NoaNai/Glosensor_assay_analysis

**Comment by szabgab** [comment]
nice, but I have a few comments:
* please rename the repo to reflect what the code will do and not "final_project" See the other projects: https://github.com/szabgab/wis-python-bootcamp-2023-12/
* Please add links to your web sites with your names as it is done here: https://github.com/goldahg/Generating-matched-patient-pairs-from-an-Excel-database/
* Include at least one input data file

**Comment by szabgab** [comment]
When you are done, please comment here.

**Comment by NoaNai** [comment]
Now updated

**Comment by szabgab** [comment]
nice
