### ISSUE TITLE
Nadav's public page

### ISSUE THREAD

**Issue by NadavMishol** [szabgab/wis-python-bootcamp-2023-12#3]
https://github.com/NadavMishol
https://github.com/NadavMishol/pythonfolder

**Comment by szabgab** [comment]
The former is a link to your github account, not to the web page created by "GitHub Pages". Given your username is `NadavMishol` you need to create a repository called `nadavmishol.github.io` and then the web site will be at http://NadavMishol.github.io/

**Comment by NadavMishol** [comment]
hello,
thank you. I've done it and now have the right website.

**Comment by NadavMishol** [comment]
oops. Here's the right URL: https://nadavmishol.github.io/

**Comment by szabgab** [comment]
better, now add some content

**Comment by NadavMishol** [comment]
Ok, added!

**Comment by szabgab** [comment]
still not a lot of content
