### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by rebeccaleghziel** [szabgab/wis-python-bootcamp-2023-12#41]
https://github.com/rebeccaleghziel/Coccolith-analysis/blob/main/README.md

**Comment by szabgab** [comment]
I cannot access that address. Is the repo maybe private? Check the "Settings" and make it public, please

**Comment by rebeccaleghziel** [comment]
I changed it to public

**Comment by szabgab** [comment]
It looks good now. Please add at least one sample input file and a link to your home page.

Enjoy the project.
