### ISSUE TITLE
Final Project - MovieFinder

### ISSUE THREAD

**Issue by NadavMishol** [szabgab/wis-python-bootcamp-2023-12#42]
Hi,
I attach my final project - MovieFinder:
https://github.com/NadavMishol/MovieFinder

Nadav

**Comment by szabgab** [comment]
Nice. I am a bit missing instructions in the README on how to us it. Do I just need to launch the Jupyter notebook? Is there anything I need to run on the command line?

**Comment by szabgab** [comment]
It would be a good idea to include the list of dependencies in a requirements.txt file, including the dependency on jupyter notebook. Then include in the instructions in the README how to set up the environment.

**Comment by szabgab** [comment]
On "Loading the data" I got this warning:

```
/home/gabor/work/MovieFinder/MovieFinder.py:27: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(gz_file, delimiter='\t', na_values='\\N', usecols = cols_to_read)
```

**Comment by szabgab** [comment]
Create a file called `.gitignore` listing the names of the files you do **not** want to be added to the repository, to make sure you do not add them accidentally. E.g.:

```
.ipynb_checkpoints/
__pycache__/
*.tsv.gz
titles.csv
```
