### ISSUE TITLE
Final project - Flow-cytometry-panel-planner

### ISSUE THREAD

**Issue by schoril** [szabgab/wis-python-bootcamp-2023-12#44]
https://github.com/schoril/Flow-cytometry-panel-planner

**Comment by szabgab** [comment]
nice

* The Python dependencies of the project should be listed in a file called requirements.txt
* There should be instructions in the README on how to set up the environment, how to run the tests and how to run the program
* There should be a file called `.gitignore` listing all the folders and files you want to exclude from git to avoid adding them accidentally.
* All the code should be in functions, even if there is a function called `main`. Functions should be short (20-40 lines max).
