### ISSUE TITLE
Final project - Protein Motif Finder

### ISSUE THREAD

**Issue by Bodya-Huri** [szabgab/wis-python-bootcamp-2023-12#48]
https://github.com/Bodya-Huri/AlphaFoldMotif

**Comment by szabgab** [comment]
I am not using Anaconda so I don't have `conda` I tried to install the depenencies using `pip install pymol` and I got:

```
ERROR: Could not find a version that satisfies the requirement pymol (from versions: none)
ERROR: No matching distribution found for pymol
```

How can I try the project?

**Comment by Bodya-Huri** [comment]
You can try using this Linux installation: https://github.com/schrodinger/pymol-open-source/blob/master/INSTALL.
This installation is directly from the git repository and is supposed to work as well.
For us, using conda was the easiest way to install pymol because of the library's complicated dependencies.

**Comment by Bodya-Huri** [comment]
Another alternative is to use `apt-get install pymol` for Ubuntu or `brew install pymol` for Mac.
This pymol wiki page has more details about the installation alternatives.

**Comment by szabgab** [comment]
OK, I also had to install `sudo apt-get install python3-biopython` and `sudo apt-get install python3-pytest`, but then it worked.
