### ISSUE TITLE
Glosensor Luciferase Assay- Noa and Ori

### ISSUE THREAD

**Issue by NoaNai** [szabgab/wis-python-bootcamp-2023-12#50]
https://github.com/NoaNai/Glosensor_assay_analysis

**Comment by szabgab** [comment]
* now that there is a `reqiorements.txt` the instruction in the README should be to run `pip install -r requirements.txt`
* `.gitignore` is empty and now are untracked folders and  files: `.ipynb_checkpoints/` that could be mistakenly added to git.
* The code should be in functions and those functions should be moved to .py files.
