### ISSUE TITLE
Final Project- Naama Zung

### ISSUE THREAD

**Issue by NaamaZung** [szabgab/wis-python-bootcamp-2023-12#51]
https://github.com/NaamaZung/fluorescent-microscopy-puncta-measurements

Thank you!

**Comment by szabgab** [comment]
* `pytest` was not among the requirements.
* After installing and running `pytest` I get the error: `FileNotFoundError: [Errno 2] No such file or directory: 'output.csv'`
* `__pycache__/` is not listed in `.gitignore`
* I don't want to write code to use this application. I would like to be able to just `python app.py` but it seems I cannot.

**Comment by NaamaZung** [comment]
Sorry for the confusion, as mentioned in the README file, test_file.py was meant to run as a script like you mentioned (`python test_file.py`) and would work with the submission code.

https://github.com/NaamaZung/fluorescent-microscopy-puncta-measurements/commit/c379f6d68da290ea50dedf56bbe2b4f02882f81c

I understand you'd like to run it in pytest, so it is now available from the latest commit:

https://github.com/NaamaZung/fluorescent-microscopy-puncta-measurements/commit/252de8c24d3168ade225d7c044d1ca144bf27e9f

Thank you for your input on the project,
Naama Zung

**Comment by szabgab** [comment]
* The one-liner functions in IO.py, especially the 2nd and the 3rd are rather unnecessary.
* There is still no main program
* The test file is still also an executable
* The test is not really a test with asserts, it just prints values to the screen
