### ISSUE TITLE
Final project - Looper - Nuria

### ISSUE THREAD

**Issue by NuriaVital** [szabgab/wis-python-bootcamp-2023-12#55]
https://github.com/NuriaVital/Looper

**Comment by szabgab** [comment]
nice work, a few comments:

* module `pandas` is not listed in requirements.txt
* by default I can't see the `Submit` button and I cannot scroll down the application. I could enlarge the window and that helped.
* When someone clicks on "open your mind" you could display one of the images from here: https://duckduckgo.com/?t=ffab&q=brain+image&iax=images&ia=images
