### ISSUE TITLE
War implications 

### ISSUE THREAD

**Issue by saritaharoni** [szabgab/wis-python-bootcamp-2023-12#56]
https://github.com/saritaharoni/War-implications

I haven't added the data files since they are confidential data from our lab.
Please let me know how can we work this out.

**Comment by szabgab** [comment]
The repository seems to be private so only invited people can see it. So you are fine with the confidentiality.

Now you need to invite me (user szabgab ) so I will also have access to it.

**Comment by saritaharoni** [comment]
I sent an invite. let me know if it works.

Thanks

**Comment by szabgab** [comment]
as this is a private project I comment about it in its repository.
