### ISSUE TITLE
TFBS finder - final project

### ISSUE THREAD

**Issue by nachshonegyes** [szabgab/wis-python-bootcamp-2023-12#57]
The repository for the project proposal was updated to include the final project and accessory files.
https://github.com/nachshon-egyes/TFBS_finder

**Comment by szabgab** [comment]
The `requirements.txt` file should only include the names of the modules, no explanation, and only the non-standard ones:

```
numpy
pandas
matplotlib
biopython
pytest
```

The readme should include instruction on how to install the requirements:: `pip install -r requirements.txt`

There should be a file called `.gitignore` listing at least this:

```
__pycache__/
output/
```

to make sure they are not added accidentally to the repository.

when I run `python tfbs_finder.py` it should tell me how to use it, not just silently quit.

I ran `python tfbs_finder.py  ex_data.csv` and got this error:

```
Traceback (most recent call last):
  File "/home/gabor/work/TFBS_finder/tfbs_finder.py", line 237, in <module>
    main()
  File "/home/gabor/work/TFBS_finder/tfbs_finder.py", line 224, in main
    test_seqs_dict = prepare_test_seqs(seq_table = seq_table, motif_stats = stats, compare = compare)
                                                                                             ^^^^^^^
UnboundLocalError: cannot access local variable 'compare' where it is not associated with a value
```

It is better to put all the Import statements to the top of the file (no `import shutil` in the middle of the code)

The compare_matches function is a bit too long and too much indentation. Consider splitting it into several functions.
